### ISSUE TITLE
heatzy pilote V2 has no climate

### ISSUE THREAD

**Issue by slicejunk** [Cyr-ius/hass-heatzy#28]
release: [5.7.1]

I have both pilote V1 and V2.

For each V1 device, 2 entities are created:   switch.xxx and climate.xxx
The V2 has only 1 switch.xx and no climate.xxx
moreover the model is set to unknown.

is there a workaround to get a climate for the V2 devices?

**Comment by slicejunk** [comment]
I guess this product key should be added to PILOTEV2 keys
46409c7f29d4411c85a3a46e5ee3703e

**Comment by arthur6703** [comment]
> I guess this product key should be added to PILOTEV2 keys 46409c7f29d4411c85a3a46e5ee3703e

Hi how did you get this key? I bought a Pilot 2 weeks ago: the version was HE0001-A. 
Now I just bought 3 others, the version changed to HE0001-B and I have the exact same error as you...

**Comment by azzu57** [comment]
> I guess this product key should be added to PILOTEV2 keys 46409c7f29d4411c85a3a46e5ee3703e

Yes, i add the key and it's work

**Comment by arthur6703** [comment]
My question was how did you get the key. 
But I contacted the support, and they got it for me . With the new key, it work for me now 👍

**Comment by slicejunk** [comment]
> My question was how did you get the key. But I contacted the support, and they got it for me . With the new key, it work for me now 👍

I requested the REST API with my credentials as explained [here](https://heatzy.com/blog/heatzy-openapi)

**Comment by slicejunk** [comment]
> > I guess this product key should be added to PILOTEV2 keys 46409c7f29d4411c85a3a46e5ee3703e
> 
> Hi how did you get this key? I bought a Pilot 2 weeks ago: the version was HE0001-A. Now I just bought 3 others, the version changed to HE0001-B and I have the exact same error as you...

HE0001-A stands for pilote V1 , HE0001-B for pilote V2

**Comment by arthur6703** [comment]
> > > I guess this product key should be added to PILOTEV2 keys 46409c7f29d4411c85a3a46e5ee3703e
> > 
> > 
> > Hi how did you get this key? I bought a Pilot 2 weeks ago: the version was HE0001-A. Now I just bought 3 others, the version changed to HE0001-B and I have the exact same error as you...
> 
> HE0001-A stands for pilote V1 , HE0001-B for pilote V2

Here is what they said :
"Le premier module que vous avez acheté correspond à la 3ème génération de pilote.
Les deux autres correspondent à la 4ème génération de pilote.
Ceux-ci fonctionnent avec les mêmes API et les mêmes fonctions que la 2nde génération."

So HE0001-A is hardware V3 ,and HE0001-B is Hardware V4. 

Thank you for the link. I just get the key by myself with the method described.

**Comment by dkroiss38** [comment]
Having the same problem here.  Might sound like a dumb question but how should I proceed to add a key to PILOTEV2?

**Comment by arthur6703** [comment]
> Having the same problem here. Might sound like a dumb question but how should I proceed to add a key to PILOTEV2?

With Visual Studio Code, open custom_components/heatzy/const.py and add the keys next to the others. For me; it looks like that:
PILOTEV2 = [
    "51d16c22a5f74280bc3cfe9ebcdc6402",
    "b9a67b6ce24b437d9794103fd317e627",
    "4fc968a21e7243b390e9ede6f1c6465d",
    "46409c7f29d4411c85a3a46e5ee3703e",
]

**Comment by dkroiss38** [comment]
Much appreciated.  Thanks.  Works perfectly now.
