### ISSUE TITLE
Add-integration don't work

### ISSUE THREAD

**Issue by Quid33** [Cyr-ius/hass-heatzy#30]
Bonjour,

Quand je clique sur "add-integration"   (a partir de : https://github.com/Cyr-ius/hass-heatzy)

J'arrive bien sur mon instance HA locale mais j'ai le message : 

```
Erreur 
Cette intégration ne prend pas en charge la configuration via l'interface utilisateur. Si vous avez suivi ce lien depuis le site web de Home Assistant, assurez-vous que vous exécutez la dernière version de Home Assistant

```
Tout est à jour :
 Home Assistant 2022.11.3 Supervisor 2022.10.2 Operating System 9.3 Interface utilisateur : 20221108.0 - latest 

Merci de votre aide !

**Comment by arthur6703** [comment]
salut, 
regarde ici: 
https://github.com/Cyr-ius/hass-heatzy/issues/29
