### ISSUE TITLE
Error fetching heatzy data

### ISSUE THREAD

**Issue by arthur6703** [Cyr-ius/hass-heatzy#33]
Hello, 
Once a day (between 1 a.m. and 7 a.m. for the moment), I have this error that occurs.:
ERROR (MainThread) [custom_components.heatzy] Error fetching heatzy data: Yuk7YkynKvBmWpG9qOCh1r not retrieved (502)

After this error, the generic thermostats that I use to control my Pilots no longer work (so if the electric heater was ON, it stays ON without ever stopping. And if it was OFF, it never turns on again ).The solution is to restart the integration when it happens.

Does anyone have an idea of the origin of the problem? (I use the Livebox integration, and the drivers always stay connected to Wifi)

**Comment by Cyr-ius** [comment]
This is an API availability problem on the web
However you can ask the generic thermostat to restart the order every x minutes with the keep_alive option

My personal setting:
   - platform: generic_thermostat
     unique_id: thermostat_living room
     name: Living Room Thermostat
     heater: group.zone_regulated
     target_sensor: sensor.lumi_rdc_temperature
     away_temp: 14
     comfort_temp: 19.5
     sleep_temp: 17.5
     hot_tolerance: 0.2
     cold_tolerance: 0.2
     keep_alive:
       minutes: 5

**Comment by ppouyet** [comment]
Never rely on web for home automation !!
