### ISSUE TITLE
Heatzy

### ISSUE THREAD

**Issue by lecomo91** [cyr-ius/hass-heatzy#34]
Hello,
I can't control the Heatzy built in schedule mode through this module.
I though it was possible to turn it on or off heater by heater and then manually manually manage the mode of the header.
But I don't find this option. In Jeedom, I found it works at least for V2 Heatzy  heater controls.
Did i miss something ?

Thanks

**Comment by Cyr-ius** [comment]
Please use beta version 5.8.1

**Comment by lecomo91** [comment]
Thank you for your prompt feedback and action.
I gave it a try and as expected, based on a chat with Heatzy support, the auto mode only works with V2 version of the heatzy module through their API.
V1 can't be controlled in auto mode using their API I was told.

Based on this statement, i can tell your beta version is working as regards as the auto mode (only works with my V2 module not the V1 - expected behavior).

I noticed tough a problem when using the OFF mode.
The OFF mode does not work anymore with the beta version with my V1 modules while it perfectly works with the stable version 5.7.2.

thanks

**Comment by Cyr-ius** [comment]
Please test 5.8.2 (fix for v1)

**Comment by cyr-ius** [comment]
Please test with  5.9.0

**Comment by lecomo91** [comment]
Thanks a lot. As far as I can tell this issue is fixed. You can close this issue.
