### ISSUE TITLE
Heatzy-Pilote ne fonctionne plus depuis HA (Pilote_Soc_C3)

### ISSUE THREAD

**Issue by nakedfoot** [cyr-ius/hass-heatzy#36]
Bonjour,

j'ai 4 Heatzy Pilote à la maison,
Tous remontés dans HA via hass-heatzy.

Tous ont correctement fonctionné jusqu'à aujourd'hui.

Les 3 modèles identifiés en "Pilote_Soc" fonctionnent toujours correctement, le modèle "Pilote_Soc_C3" ne fonctionne plus (je n'en ai qu'un, acheté après les autres).
celui qui ne fonctionne pas (firmware 04030C33) :
![image](https://user-images.githubusercontent.com/34940098/234976429-a6c97bbb-19ad-41c2-a136-005e7c434cb9.png)

un qui fonctionne toujours (firmware 04020848 ):
![image](https://user-images.githubusercontent.com/34940098/234976627-cef78eaf-c3b3-4788-b2bf-aec6051690d0.png)

comme vous le voyez, il est identifié un peu bizarrement (le child lock par ex).
Quoi que je fasse, impossible de modifier le HVAC ou le preset. Ils se remettent en "chauffe" et vide.

Je le pilote correctement depuis l'appli Heatzy.

Une update HA qui aurait des effets de bords?

Une idée ?

Merci d'avance.

**Comment by nakedfoot** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:1242
First occurred: 22:13:28 (1 occurrences)
Last logged: 22:13:28

Config entry 'heatzy (xx.xx@gmail.com)' for heatzy integration not ready yet: Cannot connect to host euapi.gizwits.com:443 ssl:default [Try again]; Retrying in background

et


Logger: custom_components.heatzy.climate
Source: custom_components/heatzy/climate.py:192
Integration: Heatzy ([documentation](https://github.com/cyr-ius/hass-heatzy), [issues](https://github.com/cyr-ius/hass-heatzy/issues))
First occurred: 21:32:19 (8 occurrences)
Last logged: 22:15:14

Set preset mode (comfort) Command failed crNZGSeob6mxbAnryRmD27 {'attrs': {'mode': 'cft'}} (400 BAD REQUEST) (Canapé Salon)
Set preset mode (heat) Command failed crNZGSeob6mxbAnryRmD27 {'attrs': {'mode': None}} (400 BAD REQUEST) (Canapé Salon)
Set preset mode (none) Command failed crNZGSeob6mxbAnryRmD27 {'attrs': {'mode': 'stop'}} (400 BAD REQUEST) (Canapé Salon)
Set preset mode (eco) Command failed crNZGSeob6mxbAnryRmD27 {'attrs': {'mode': 'eco'}} (400 BAD REQUEST) (Canapé Salon)

**Comment by cyr-ius** [comment]
Essayer avec la nouvelle version 5.8.5

**Comment by cyr-ius** [comment]
Fix to 5.8.9 version (Beta)
