### ISSUE TITLE
Being able to set heatzy in program mode

### ISSUE THREAD

**Issue by antro31** [cyr-ius/hass-heatzy#39]
Thanks a lot for this integration. 
Is there a way through heatzy API to be able to set the heatzy (pilot in my case) in program mode? (Meaning that it automatically runs the programs). 

Thanks,

**Comment by cyr-ius** [comment]
The point is to program it with HA

**Comment by antro31** [comment]
The point is being able to activate the program stored in the Heatzy (and not to program it through HA). 
The advantage of this is that it does not depend on HA availability and program is stored in the heatzy itself. 

BTW, I managed to do it by myself. 
By posting to `https://euapi.gizwits.com/app/control/{{did}}` the following content:
`{"attrs":{"timer_switch":0}}`

Heatzy will disable the scheduler. 
To enable it, post the following: 
`{"attrs":{"timer_switch":1}}`


To get the status, 
send a GET to the following `https://euapi.gizwits.com/app/devdata/{{did}}/latest`
and get the value of attr.timer_switch

Of course, to do all of these, you need to know you {{did}} (device id), and get a token prior to sending any command

**Comment by cyr-ius** [comment]
You can use the latest version 5.8.9 (beta).
A new mode has appeared: Auto mode which allows you to let the Heatzy application do automatic programming
On the other hand, if you exit Auto mode in HA, this deactivates the timer_switch.

**Comment by antro31** [comment]
Exactly what I was looking for ! Thanks.
