### ISSUE TITLE
Heatzy bloom

### ISSUE THREAD

**Issue by lecomo91** [cyr-ius/hass-heatzy#40]
Hello,
I bought a BLOOM (not Glow) and it can't be found by the module.

Is there a possibility to manage it in a future release ?

Thanks

**Comment by cyr-ius** [comment]
Il nous faudrait la clé du produit
voir https://github.com/cyr-ius/hass-heatzy/blob/5.8.2/custom_components/heatzy/const.py

**Comment by cyr-ius** [comment]
Please execute "Download Diagnostic" from last release 5.8.4 and post file in this issue
![image](https://github.com/cyr-ius/hass-heatzy/assets/1258123/8f477626-c71f-4643-b433-6e97bef25fb4)

**Comment by lecomo91** [comment]
Is it what you need ?

          "mcu_soft_version": "00000001",
          "product_key": "480253852d574f11b2d7fbf4460d7a41",
          "state_last_timestamp": 1698317370,
          "role": "special",
          "is_sandbox": false,
          "type": "normal",
          "product_name": "Bloom",
          "is_disabled": false,
          "mcu_hard_version": "00000001",
          "wifi_soft_version": "04020037",

**Comment by cyr-ius** [comment]
I would have preferred to have the diagnostic file to know its exact behavior. (with or without temperature)
I have just declared the key as with the traditional convector (comfort, eco, frost protection)

Please give me feedback if it's good.

**Comment by lecomo91** [comment]
Is it possible to send you the file in private ?

I tested the new version 5.9.0 and although now it appears  as a climate entity, changing the settings has no effect on Heatzy app.

**Comment by cyr-ius** [comment]
Oups... Fix from 5.9.1
Vous pouvez télécharger le fichier publiquement, car tout ce qui est sensible a été censuré (ces valeurs sont remplacées par le mot ***SUPPRIMÉ***)

**Comment by lecomo91** [comment]
[config_entry-heatzy-6f3e92c009de236d56c542add0e533a7.json.txt](https://github.com/cyr-ius/hass-heatzy/files/13178493/config_entry-heatzy-6f3e92c009de236d56c542add0e533a7.json.txt)

**Comment by cyr-ius** [comment]
In fact you have V1 and V2 convectors, and the Bloom is seen as a V2. The association is with version V2 is the correct one. THANK YOU

**Comment by lecomo91** [comment]
Hi,

I checked the latest version 5.9.1 but it is still not updating the settings back to Heatzy for the Bloom heater.
Thanks for your help on this.

**Comment by cyr-ius** [comment]
ok, I understand, it's a completely different model, I just created a specific class.
Can you try version 5.9.2 (which is in beta in HACS) and tell me the behavior
Current temperature, Eco and Comfort temperature updates as well as preset management and off/on

**Comment by lecomo91** [comment]
Well now the device is unavailable.
Please let me know how I can help further.
Thanks

**Comment by cyr-ius** [comment]
Please try 5.9.4

**Comment by lecomo91** [comment]
Hi,
I just tested it.
This is much better as I receive the values from Heatzy including the temperatures.
If I modify it i Heatzy then it gets updated in HA.

But the opposite is not true.
When I change the hvac or preset mode values in HA, the information is not updated back in Heatzy.

Thanks

**Comment by orionevo14** [comment]
Hello,
Same here, same model "480253852d574f11b2d7fbf4460d7a41" and same behavior : from Heatzy to HA, update is fine but no update possible from HA. That means I'm not able to change the temperature or to start heating the room from HA.
I've got this error when I try to change the temp from HA :
Error to set temperature: Command failed control/wZyaTKd4vzQfSBktVEdE4F with {'json': {'attrs': {'com_temp': 5.0, 'eco_temp': 5.0}}} (400 BAD REQUEST)

Thank you for your work.

**Comment by cyr-ius** [comment]
When I read the manufacturer's documentation, it does not seem possible to adjust the temperature. Can you change this in the Heatzy app?

Additionally, finding the right setting won't be easy, because Heatzy doesn't document the APIs for these models.

**Comment by orionevo14** [comment]
Yeah it's possible in the Heatzy app.
I wrote to the support and they told me that the API is the same as the Pilote, but every attemp I make trying to start the heater in comfort or any other mode through Postman is a failure (with mode: 0 or mode: cft). I'm waiting for another answer now but I'm not really confident...

**Comment by cyr-ius** [comment]
Please test 5.9.6-beta5 , i convet float number to integer

**Comment by orionevo14** [comment]
Not better, and still not possible to start heating : 
Error to set temperature: Command failed control/wZyaTKd4vzQfSBktVEdE4F with {'json': {'attrs': {'com_temp': 25, 'eco_temp': 5}}} (400 BAD REQUEST)
I'll let you know the answer of the support, if any...

**Comment by lecomo91** [comment]
Hello,
I tried the latest beta version but then all devices appear as not available so I switched back to 5.9.6
Not sure how I can help providing the error logs.

**Comment by orionevo14** [comment]
Hi,
I can change the temperature within Postman using those attributes :
{
    "attrs": {
    "cft_temp": 15,
    "eco_temp": 8
    }
}
In the error message of the integration in HA I see "com_temp" instead of "cft_temp", is that the problem ?

I still can't start the heater though.

**Comment by lecomo91** [comment]
I installed Postman and tried to run the API over my BLOOM heater to check. And obvisouly Send_order_pilote2&3 is not working with it. I tried to post "mode" and nothing happens.
I have a module 2 and for this one it is working fine. So I guess their API is buggy with BLOOM.
I sent an email to their support.

**Comment by lecomo91** [comment]
Tsting more with Postman, I agree with orionevo14 that the temperatures can be changed this way:

**Comment by cyr-ius** [comment]
Please try 5.9.7-beta3  , I replaced the com_temp value with cft_temp

**Comment by lecomo91** [comment]
The temp are now working and updating in Heatzy. 
However when I reload the screen with temp in HA, it corretly gets the eco_temp from Heatzy but not the cft_temp.
It always displays cft_temp with 6°C so I think this cft_temp is not retrieved from Heatzy back to HA.

**Comment by cyr-ius** [comment]
I don't know why from the beginning, I skipped the cft_temp attribute even though it is in the diagnostic file.
I fixed it, the displayed value must be correct

**Comment by lecomo91** [comment]
Thank you. The temperatures are working great with the latest beta.
I am still in touch with Heatzy support so they can check why "mode" update is not workng with the API.
They are supposed to forward my message to the dev.

**Comment by orionevo14** [comment]
Same thing here, my issue is forwarded to the dev team.
