### ISSUE TITLE
API with error code 500 - 502 (Unavailable device)

### ISSUE THREAD

**Issue by JGitHubB** [cyr-ius/hass-heatzy#41]
Integration works great. But as you can on these logs, around every hour Heatzy becomes unavailable, which messes up the timeline..
Seems like something drops regularly.
![image](https://github.com/cyr-ius/hass-heatzy/assets/6003899/268623e8-5e76-4592-86f3-58e5228b8764)

**Comment by hombre-13hb** [comment]
Hi, I've got roughly the same issue. Anything I can do to fix it ?
Thanks

**Comment by cyr-ius** [comment]
You must activate Debug mode to find out more

**Comment by cyr-ius** [comment]
Please , test with 5.9.0

**Comment by JGitHubB** [comment]
Enabled debug mode + updating to 5.9. Will let you know.

**Comment by hombre-13hb** [comment]
Hi, installed 5.9 but entities keep being unavailable regularly making automation impossible to use. What can I provide to help ?

**Comment by JGitHubB** [comment]
Same there with 5.9.7

**Comment by cyr-ius** [comment]
Un mode Websocket extrêment performant , à tester en sélectionnant les versions commençant par : ws- 
En activant le mode Beta dans HACS 
Première sortie : ws-6.1.0
Résoud les problèmes d'erreur : 500 , 502

**Comment by cyr-ius** [comment]
Fiw with beta version, please test
