### ISSUE TITLE
Heatzy Pilote (Pilote_Soc_C3) return null in current_temperature

### ISSUE THREAD

**Issue by LouisForaux** [cyr-ius/hass-heatzy#42]
Hello,

The Pilote_Soc_C3 return a null value for current_temperature in HA.

I'm on the latest version of HA, HASS-Heatzy, HASS and on the Heatzy device itself (I believe, I've no information for a potential update)

Have a good day

**Comment by cyr-ius** [comment]
You must activate Debug mode to find out more

**Comment by cyr-ius** [comment]
Fix to 5.8.9 version (Beta)

**Comment by LouisForaux** [comment]
Thanks !

Now I have no more "Current_temperature"

Maybe you can add the possibility to link an optional (and external) thermometer? 
It can be useful for the climate entity and for showing purposes.

**Comment by Mysa95** [comment]
What a great job ! 👏 

Add an external thermometer can be very useful !!
I use also the HomeKit integration and i don’t have the access of the preset modes. Do you know if we can add this ? :)
