### ISSUE TITLE
Heatzy Onyx

### ISSUE THREAD

**Issue by lugio** [cyr-ius/hass-heatzy#43]
Hello,

The Onyx radiator is currently not compatible with the project.
I have two Heatzy Onxy radiators and am willing to assist with testing or any other non-coding tasks.
I do not have coding skills.

[config_entry-heatzy-64670c2d97037e2f2f296aa0671c48f0.json.txt](https://github.com/cyr-ius/hass-heatzy/files/13169794/config_entry-heatzy-64670c2d97037e2f2f296aa0671c48f0.json.txt)

The data appears to be coming through, but the integration is not recognizing it.

product_key": "bb10d064f8de409db633b750faa22a52"

Here is what is currently being sent to Home Assistant.
![image](https://github.com/cyr-ius/hass-heatzy/assets/25223566/700db2aa-3f64-49a4-9757-567809feae0e)

**Comment by cyr-ius** [comment]
After analyzing the file, I think they have the same characteristics as the Glow model.
I just added the key in version 5.8.7
Please come back to me

**Comment by lugio** [comment]
Parfait :) 

![image](https://github.com/cyr-ius/hass-heatzy/assets/25223566/8fa3dbb3-a415-473e-aca3-0a63d48af60b)

Thanks !

**Comment by lugio** [comment]
Hello, 

sur la version 5.9 plus de climate sensor

![image](https://github.com/cyr-ius/hass-heatzy/assets/25223566/71f8a0a6-a91e-4888-b393-a5e4a482e0ef)
