### ISSUE TITLE
Heatzy Onyx (v5.9.0)

### ISSUE THREAD

**Issue by lugio** [cyr-ius/hass-heatzy#45]
Hello, 

sur la version 5.9 plus de climate sensor

![image](https://github.com/cyr-ius/hass-heatzy/assets/25223566/71f8a0a6-a91e-4888-b393-a5e4a482e0ef)

_Originally posted by @lugio in https://github.com/cyr-ius/hass-heatzy/issues/43#issuecomment-1781116353_

**Comment by cyr-ius** [comment]
Fix in 5.9.1
