### ISSUE TITLE
Add support for boost mode

### ISSUE THREAD

**Issue by ellmout** [cyr-ius/hass-heatzy#46]
Hi Cyr-ius,

Can you add support for the boost mode for the Heatzy Pilote v2 ?

You can switch boost mode on by setting derog_mode to 2 and derog_time to 30min, or 60 min, or what you want.

You can't find it in the heatzy api documentation, but there is blog post about it (in french, sorry) :

https://heatzy.com/blog/communaute-siri-boost

I made a fork a month ago with boost mode :

https://github.com/ellmout/hass-heatzy/tree/feature-boost-mode

but your code change a lot since.

Thx

**Comment by cyr-ius** [comment]
The boost mode is based on a timer of 30 or 60 min, it would rather be a service that allows people to choose the duration

**Comment by ellmout** [comment]
I have Wiser thermostat and you can set the boost mode like this : 

![image](https://github.com/cyr-ius/hass-heatzy/assets/4562782/f81cfc1a-e42d-4c1e-877e-6399321da494)

**Comment by cyr-ius** [comment]
Please test 5.9.7-beta0
Boost services and vacations services
Boost preset

**Comment by ellmout** [comment]
Setting boost mode is ok !
But when i switch back to eco, it stays on boost mode !
In the app, it stays on boost mode too.
Thx!

**Comment by cyr-ius** [comment]
Fix into 5.9.7-beta1
