### ISSUE TITLE
Add Conf-1 and Conf-2 modes (6 orders)

### ISSUE THREAD

**Issue by Mysa95** [cyr-ius/hass-heatzy#47]
Hello👋!
Thanks for all you do on this integration :).
I saw that you can use 2 other modes in the Heatzy api. When you hold down the moon, modes -1 and -2 appear. These 2 modes appear as Conf-1 and Conf-2 on my Sauter radiator and allow me to set 2 temperatures in addition to the comfort and eco ones.

Do you know if it's possible to add these two modes to your integration?

Have a nice day :)
![IMG_6228](https://github.com/cyr-ius/hass-heatzy/assets/123031600/cda90759-44fa-4936-b985-223f6f36192b)

**Comment by cyr-ius** [comment]
Please upload  a diagnostic file to this issue

![image](https://github.com/cyr-ius/hass-heatzy/assets/1258123/590bd068-74b6-4f45-ba3c-4809382c6aa5)

Submit two diagnostic files, one file with some settings and another file after changing some settings. This allows you to find the right values.

**Comment by Mysa95** [comment]
Hello,

You will find bellow the following diagnostics:
- SETUP 1 = **Comfort** mode activated on my devices
- SETUP 2 = **Comfort-1** mode activated on my devices (by the Heatzy app)
- SETUP 3 = **Comfort-2** mode activated on my devices (also by the Heatzy app)

I compare these files on notepad and i saw these differencies:
 - SETUP 1 = "mode": "**cft**"
 - SETUP 2 = "mode": "**cft1**"
 - SETUP 3 = "mode": "**cft2**"

[SETUP_1_config_entry-heatzy-166fe5c35337253e946f2535fdcd10ff.json.txt](https://github.com/cyr-ius/hass-heatzy/files/13389484/SETUP_1_config_entry-heatzy-166fe5c35337253e946f2535fdcd10ff.json.txt)
[SETUP_2_config_entry-heatzy-166fe5c35337253e946f2535fdcd10ff.json.txt](https://github.com/cyr-ius/hass-heatzy/files/13389481/SETUP_2_config_entry-heatzy-166fe5c35337253e946f2535fdcd10ff.json.txt)
[SETUP_3_config_entry-heatzy-166fe5c35337253e946f2535fdcd10ff.json.txt](https://github.com/cyr-ius/hass-heatzy/files/13389483/SETUP_3_config_entry-heatzy-166fe5c35337253e946f2535fdcd10ff.json.txt)

**Comment by cyr-ius** [comment]
Can you give me the exact name of the radiator to reference it correctly, does this model also allow you to adjust the temperature in degrees?

Please test 5.9.6-beta4 , i add comfort 1, 2 into preset
Please get back to me

**Comment by Mysa95** [comment]
Hi,

I tried the 5.9.6-beta5 and it works perfectly !
Just some extra informations regarding these two modes.

- Comfort-1 is Comfort temperature - 1°c
- Comfort-2 is Comfort temperature - 2°c.
So we do not have the possibility to set a specific temperature for each mode, it’s automatically calculated based on the Comfort temperature (temperature de consigne). 

It works really good with my radiator (SAUTER OROSI) > https://media.adeo.com/marketplace/LMFR/80162919/1230237.pdf?otConsentString=C0001:1,C0002:0,C0002:0,C0003:0,C0004:0,C0005:0

I think it will work with any radiator who accepts the 6 orders Pilot command.

Thank you for this upgrade ! You rock !

**Comment by Mysa95** [comment]
> Hi,
> 
> I tried the 5.9.6-beta5 and it works perfectly ! Just some extra informations regarding these two modes.
> 
> * Comfort-1 is Comfort temperature - 1°c
> * Comfort-2 is Comfort temperature - 2°c.
>   So we do not have the possibility to set a specific temperature for each mode, it’s automatically calculated based on the Comfort temperature (temperature de consigne).
> 
> It works really good with my radiator (SAUTER OROSI) > https://media.adeo.com/marketplace/LMFR/80162919/1230237.pdf?otConsentString=C0001:1,C0002:0,C0002:0,C0003:0,C0004:0,C0005:0
> 
> I think it will work with any radiator who accepts the 6 orders Pilot command.
> 
> Thank you for this upgrade ! You rock !

I just find an issue. 
When I switch from Confort-2 to Confort, the preset on the climate entity stay on Confort 2 but it switch well to confort on my radiators and also on Heatzy app.

**Comment by cyr-ius** [comment]
please test 5.9.6

**Comment by Mysa95** [comment]
I tried and that’s my feedback:
- All of the presets works fine
- Some issues with the actualisation of the activated preset. For example, when I switch from Confort 2 to Away, Heatzy app switch well to Away but the preset in HA stay on Confort 2. So sometimes, HA indicates the previous preset and not the activated preset (Maybe an actualisation issue between HA and Heatzy app…)

**Comment by cyr-ius** [comment]
The API reacts a little long, and like HA scans every 60 seconds, to have the updated status, you sometimes have to wait for two scan intervals, i.e. 2 minutes

**Comment by Mysa95** [comment]
Perfect ! Thank you for this information and the upgrade ! :)

issue solved !
