### ISSUE TITLE
Status update delay set to 10 sec.s

### ISSUE THREAD

**Issue by luke7101** [cyr-ius/hass-heatzy#49]
Hi, probably not a bug but ...

I observed from the logs and code that heatzy servers are scanned every 60 seconds for device status.
When a order is sent from HA to heatzy its effect is almost immediate and their native app is almost immediately updated, however the device status in HA isn't updated in real time and this delay causes a feeling of slowness and lagginess ...
In fact the update is only triggered after a 10 seconds delay. I suppose there's a reason for that, however isn't it possible to adjust it ?

Thanks

**Comment by cyr-ius** [comment]
No, this is not possible because otherwise we risk a denial of service on Heatzy's servers. and occupied too much CPU at HomeAssistant.
I stay on 1min which is very good for a sensor

**Comment by luke7101** [comment]
Le délai du poll à 1 minute est tout à fait raisonnable, je suis d'accord.
J'entendais le délai de 10 sec. (que tu appelles cooldown je crois) qui fait qu'une commande envoyée de HA vers heatzy déclenche une mise à jour "anticipée" de l'état des dispositifs.
Je trouve que c'est un peu long de devoir attendre 10 secondes pour avoir une confirmation de la bonne prise en compte de la commande envoyée, surtout dans le contexte où certains dispositifs ne répondent pas aux API et retournent des erreurs.
2 secondes est peut être trop rapide, 3 secondes me semble pas mal.

**Comment by cyr-ius** [comment]
Si tu veux un addon performant , je viens de sortir une version beta nommé ws-6.1.0 , elle se base sur le websocket et la prise en compte est immédiat
Dans HACS  , activé le mode beta et choisir les versions commençait par ws-X.X.X
