### ISSUE TITLE
Mode Websocket - [Beta-testeur] - Faites vos retours - Feedback Issue

### ISSUE THREAD

**Issue by cyr-ius** [cyr-ius/hass-heatzy#52]
Vos retours dans cette issue , si vous testez le mode Websocket
Your feedback in this issue, if you test Websocket mode

Pour retrouver ces versions , dans HACS  activé le mode Beta , et selectionner les versions commençant par ws-
Première sortie : ws-6.1.0
To find these versions, in HACS activated Beta mode, and select the versions starting with ws-
First release: ws-6.1.0

**Comment by terzo13** [comment]
Salut,
Encore merci pour tout le boulot que tu fais. 
Chez moi, la nouvelle version en ws-... ne fonctionne pas, même erreur que pendant l'incident de la semaine dernière.
Je suis en haos direct sur un khadas vim3.
Si besoin d'autres infos dis moi.
Bonne soirée

**Comment by cyr-ius** [comment]
Je viens de corriger la version pour avoir une remonté d'état au petit oignon. Diste moi sic'est mieux
A tester ws-6.1.2

**Comment by gael1980** [comment]
Je le teste depuis ce matin.
Pas de problème pour l'instant

**Comment by Fly0017** [comment]
Idem, je m'en sers depuis hier (et ce matin la 6.1.2), aucun souci à remonter au contraire c'est ultra top d'avoir un truc aussi réactif, merci beaucoup !

**Comment by luke7101** [comment]
Pareil ici, ça marche très bien cette version ws ! Faut tester sur une plus longue durée mais en tout cas pour l'instant c'est très prometteur ! 
Je la préfère nettement à la version API en tout cas

**Comment by cyr-ius** [comment]
Pour info , je viens de publier la version ws-6.1.3 , seule modification ,  passage en TLS.

De mon côté pareil aucun soucis, particulier. 
Le seul doute , c'est le control d'un module Pilote v1 
les modules qui ont le product key : 9420ae048da545c88fc6274d204dd25f

Car l'appel pour passer les ordres est pas le même et je possède pas ce modèle.

**Comment by Fly0017** [comment]
Je viens de mettre à jour, tout fonctionne toujours pour moi, et toujours aussi instantané. 

Et pour le moment aucun souci, et aucune erreur dans les logs.

**Comment by valdogazal** [comment]
Parfait également pour moi, en 6.1.2 et 6.1.3. J’ai enfin mon module qui fonctionne. Je commençais à regretter mon achat. 
merci pour ton boulot 👍

**Comment by luke7101** [comment]
Petit point après 3 jours, globalement ça marche du feu de dieu !
Parfois j'ai un ou 2 dispositifs sur 5 auxquels j'envoie une commande et rien ne se passe. Je consulte l'appli officielle au même moment et ces dispositifs sont grisés, comme injoignables (pourtant bien connectés en wifi d'après le routeur).
En tout cas s'ils ne sont pas sur l'appli officielle il est normal qu'il ne se passe rien côté intégration.
Donc dans l'absolu je suis super content de cette version qui marche au mieux de ce qu'il est possible de faire avec ces appareils à mon avis!
Encore merci 👍

**Comment by cyr-ius** [comment]
Merci pour vos retours, c est toujours encourageant d avoir du positif. Je vais voir comment embarquer le mode websocket dans la branche standard de Heatzy. 
Je penses que je vais embarquer le code en dormant et activable via une options du config flow. Cela permettra a chacun de continuer de faire de teste et de passer d'un mode à l autre.
Et au printemps, on bascule en full websocket. Moins critique le chauffage a cette période.

On m a poser la question concernant l appli du smartphone si elle utilisait le websocket.
Effectivement je pense que c est le cas , coté Android et iOS on a quasiment aucun appel sur l api https. Et le websocket est monté , d'où les comportements qui semblent cohérent à l usage.

Du coup , je vais sortir une ultime beta ws-  avec l option dans le config-flow (mode websocket activé par défaut). Comme ça vous pourrez tester la future version de prod. Et ensuite je publierai la meme sur la branche standard en changeant juste la valeur par défaut.

**Comment by cyr-ius** [comment]
Cerise sur le gateau si dans cette future beta , vous choisissez de rester en mode websocket. Quand nous reviendrons sur la version standard, vous garderez ce mode dans le config-flow

**Comment by luke7101** [comment]
Top 👍 !

**Comment by magicbret** [comment]
Hello, et merci pour le boulot.
Alors moi je rencontre un soucis mais je ne pense pas que ce soit lié au mode websocket (du coup je devrais peut-être ouvrir un nouveau thread)

J'ai 4 boitiers, dont 2 semblent ne pas avoir le même software embarqué (pure supposition). 
Si je regarde le "modèle d'appareil" dans HA, 2 boitiers ont comme modèle "Pilote_Soc" et 2 autres "Heatzy". 

<img width="903" alt="Capture d’écran 2024-01-10 à 18 01 46" src="https://github.com/cyr-ius/hass-heatzy/assets/7100026/ff3be15a-31f7-4502-8dfb-74f42f918181">

Pour les 2 "Pilote_Soc", les changements de mode (eco, chauffe ou Off) fonctionne très bien. En revanche, pour les 2 autres boitiers ayant pour modèle "Heatzy", rien ne se passe lorsque je veux changer l'état. 

En revanche, si je change via l'appli officiel, l'état dans HA change instantanément. 

Le problème viendrait donc lors de l'envoi des commandes depuis HA. Une idée du problème ?

**Comment by lb544** [comment]
Bonjour,
Tout d'abord merci pour cette intégration !

Je rencontre un problème depuis quelques temps, je n'ai que le lock qui fonctionne et qui remonte comme switch pour un Heatzy Fil Pilote 

Aucun autre mode n'est possible

Testé sur la dernière version stable et également la beta WS
![Screenshot_20240110_201332_heatzy](https://github.com/cyr-ius/hass-heatzy/assets/56821713/ab2d82c6-8e16-4f78-a456-e8cde42408ce)
![Screenshot_20240110_201345_Home Assistant](https://github.com/cyr-ius/hass-heatzy/assets/56821713/9b8ca067-f897-4e6a-95fa-707a548bcf53)
![Screenshot_20240110_201354_Home Assistant](https://github.com/cyr-ius/hass-heatzy/assets/56821713/8ab2a275-564f-4ddb-a9d2-a9b4e53f28d4)
![Screenshot_20240110_201401_heatzy](https://github.com/cyr-ius/hass-heatzy/assets/56821713/df0bb12e-51dc-4fbf-82e7-c64f1bcff4f9)

Merci

**Comment by magicbret** [comment]
> Hello, et merci pour le boulot.
> 
> Alors moi je rencontre un soucis mais je ne pense pas que ce soit lié au mode websocket (du coup je devrais peut-être ouvrir un nouveau thread)
> 
> 
> 
> J'ai 4 boitiers, dont 2 semblent ne pas avoir le même software embarqué (pure supposition). 
> 
> Si je regarde le "modèle d'appareil" dans HA, 2 boitiers ont comme modèle "Pilote_Soc" et 2 autres "Heatzy". 
> 
> 
> 
> <img width="903" alt="Capture d’écran 2024-01-10 à 18 01 46" src="https://github.com/cyr-ius/hass-heatzy/assets/7100026/ff3be15a-31f7-4502-8dfb-74f42f918181">
> 
> 
> 
> Pour les 2 "Pilote_Soc", les changements de mode (eco, chauffe ou Off) fonctionne très bien. En revanche, pour les 2 autres boitiers ayant pour modèle "Heatzy", rien ne se passe lorsque je veux changer l'état. 
> 
> 
> 
> En revanche, si je change via l'appli officiel, l'état dans HA change instantanément. 
> 
> 
> 
> Le problème viendrait donc lors de l'envoi des commandes depuis HA. Une idée du problème ? 

Pour info, j'ai re basculé sur la version 5.9.7 et les commandes fonctionnent de nouveau pour les boîtiers dont le modèle est "Heatzy"
Il y aurait une incompatibilité entre les 2 modèles de boîtiers Heatzy Pilot et la version websocket ?

**Comment by cyr-ius** [comment]
> > Hello, et merci pour le boulot.
> > Alors moi je rencontre un soucis mais je ne pense pas que ce soit lié au mode websocket (du coup je devrais peut-être ouvrir un nouveau thread)
> > J'ai 4 boitiers, dont 2 semblent ne pas avoir le même software embarqué (pure supposition).
> > Si je regarde le "modèle d'appareil" dans HA, 2 boitiers ont comme modèle "Pilote_Soc" et 2 autres "Heatzy".
> > <img alt="Capture d’écran 2024-01-10 à 18 01 46" width="903" src="https://private-user-images.githubusercontent.com/7100026/295645609-ff3be15a-31f7-4502-8dfb-74f42f918181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjM0MDQsIm5iZiI6MTcwNDkyMzEwNCwicGF0aCI6Ii83MTAwMDI2LzI5NTY0NTYwOS1mZjNiZTE1YS0zMWY3LTQ1MDItOGRmYi03NGY0MmY5MTgxODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMjE0NTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2NhYTlhOWJkMGRlMTQ5ZTNlNDA4ZDM1ZDcyZTU3M2NkNDdlY2Y1ZGIzNWQ1MDgyNGEwMjljYTYyOWRkMTJlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xsxAYyUSVfILzYonvlGZaScnJBUk7zZRRen9u1BRsMo">
> > Pour les 2 "Pilote_Soc", les changements de mode (eco, chauffe ou Off) fonctionne très bien. En revanche, pour les 2 autres boitiers ayant pour modèle "Heatzy", rien ne se passe lorsque je veux changer l'état.
> > En revanche, si je change via l'appli officiel, l'état dans HA change instantanément.
> > Le problème viendrait donc lors de l'envoi des commandes depuis HA. Une idée du problème ?
> 
> Pour info, j'ai re basculé sur la version 5.9.7 et les commandes fonctionnent de nouveau pour les boîtiers dont le modèle est "Heatzy" Il y aurait une incompatibilité entre les 2 modèles de boîtiers Heatzy Pilot et la version websocket ?

@magicbret , je pense que tu as bien un soucis autour du websocket. Il existe effectivement deux modèles d appel.
J ai codé le websocket pour les deux modes mais ne possedant  pas le premier modèle  de matériels, je n ai pas pu tester.
Avant de se lancer plus en avant de l éventualité d une correction, peux tu déposer le fichier de dagnostic pour être sur.

**Comment by cyr-ius** [comment]
@lb544 ,  si cela ne marche ni surla version normal, ni sur la version websocket
Tu as un  sous-modèle non référencer. Il faut que tu ouvre une nouvelle issue.
Tu précises bien le modèle que tu as , photo liens vers un site référençant ton modèle et dans l issue , tu déposes le fichier de diagnostic. En l'absence de fichier , je peux rien faire

**Comment by magicbret** [comment]
> > > Hello, et merci pour le boulot.
> > > Alors moi je rencontre un soucis mais je ne pense pas que ce soit lié au mode websocket (du coup je devrais peut-être ouvrir un nouveau thread)
> > > J'ai 4 boitiers, dont 2 semblent ne pas avoir le même software embarqué (pure supposition).
> > > Si je regarde le "modèle d'appareil" dans HA, 2 boitiers ont comme modèle "Pilote_Soc" et 2 autres "Heatzy".
> > > <img alt="Capture d’écran 2024-01-10 à 18 01 46" width="903" src="https://private-user-images.githubusercontent.com/7100026/295645609-ff3be15a-31f7-4502-8dfb-74f42f918181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjM0MDQsIm5iZiI6MTcwNDkyMzEwNCwicGF0aCI6Ii83MTAwMDI2LzI5NTY0NTYwOS1mZjNiZTE1YS0zMWY3LTQ1MDItOGRmYi03NGY0MmY5MTgxODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMjE0NTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2NhYTlhOWJkMGRlMTQ5ZTNlNDA4ZDM1ZDcyZTU3M2NkNDdlY2Y1ZGIzNWQ1MDgyNGEwMjljYTYyOWRkMTJlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xsxAYyUSVfILzYonvlGZaScnJBUk7zZRRen9u1BRsMo">
> > > Pour les 2 "Pilote_Soc", les changements de mode (eco, chauffe ou Off) fonctionne très bien. En revanche, pour les 2 autres boitiers ayant pour modèle "Heatzy", rien ne se passe lorsque je veux changer l'état.
> > > En revanche, si je change via l'appli officiel, l'état dans HA change instantanément.
> > > Le problème viendrait donc lors de l'envoi des commandes depuis HA. Une idée du problème ?
> > 
> > 
> > Pour info, j'ai re basculé sur la version 5.9.7 et les commandes fonctionnent de nouveau pour les boîtiers dont le modèle est "Heatzy" Il y aurait une incompatibilité entre les 2 modèles de boîtiers Heatzy Pilot et la version websocket ?
> 
> @magicbret , je pense que tu as bien un soucis autour du websocket. Il existe effectivement deux modèles d appel. J ai codé le websocket pour les deux modes mais ne possedant pas le premier modèle de matériels, je n ai pas pu tester. Avant de se lancer plus en avant de l éventualité d une correction, peux tu déposer le fichier de dagnostic pour être sur.

Le fichier de diag en pièce jointe. Merci :)
[config_entry-heatzy-5cfe5470bb8f0612e705c215359934ae.json(1).txt](https://github.com/cyr-ius/hass-heatzy/files/13901101/config_entry-heatzy-5cfe5470bb8f0612e705c215359934ae.json.1.txt)

**Comment by cyr-ius** [comment]
@magicbret  , après vérification , tu es exactement  dans ce cas , les modules nommé "heatzy" sont les modules de première génération qui avait un appel spécifique. 

Pour exemple, dans l'api https , pour la première génération de module on devait passer un json sous le format:
{"raw": [1,1,3]} 
pour ordonner l'arrêt du convecteur. Alors que pour les générations suivantes , on doit passer
{"attrs": {"mode": "stop"}}

Comme annoncer , je vais sortir une nouvelle beta version ws-6.1.4 dans la journée. Il faudra essayer avec celle-ci et me dire si cela fonctionne. Si cela fonctionne pas , il faut me redéposer le fichier de daignostic car j'incluerai de fait des tests supplémentaire dans ce fichier.

**Comment by magicbret** [comment]
> @magicbret , après vérification , tu es exactement dans ce cas , les modules nommé "heatzy" sont les modules de première génération qui avait un appel spécifique.
> 
> Pour exemple, dans l'api https , pour la première génération de module on devait passer un json sous le format: {"raw": [1,1,3]} pour ordonner l'arrêt du convecteur. Alors que pour les générations suivantes , on doit passer {"attrs": {"mode": "stop"}}
> 
> Comme annoncer , je vais sortir une nouvelle beta version ws-6.1.4 dans la journée. Il faudra essayer avec celle-ci et me dire si cela fonctionne. Si cela fonctionne pas , il faut me redéposer le fichier de daignostic car j'incluerai de fait des tests supplémentaire dans ce fichier.

👍 super merci pour tout le boulot que tu fais. Je ferais un retour dès que dispo et que j'aurais mis à jour.

**Comment by cyr-ius** [comment]
La dernière beta ws-6.1.4 est disponible, comme annoncer  elle n'apporte pas de nouveauté en soit sur le mode websocket (ou peut être le correctif de modèle v1 que @magicbret  doit vérifier)
La nouveauté majeure est de pouvoir choisir entre le mode weboscket ou le mode standard.
Comme annoncer l'objectif est que cette version deviennent la version officielle.

Je suis preneur de vos retours pour vérifier qu'il n'y a pas des regressions vis à vis des comportements.

**Comment by magicbret** [comment]
> La dernière beta ws-6.1.4 est disponible, comme annoncer elle n'apporte pas de nouveauté en soit sur le mode websocket (ou peut être le correctif de modèle v1 que @magicbret doit vérifier) La nouveauté majeure est de pouvoir choisir entre le mode weboscket ou le mode standard. Comme annoncer l'objectif est que cette version deviennent la version officielle.
> 
> Je suis preneur de vos retours pour vérifier qu'il n'y a pas des regressions vis à vis des comportements.

Alors voici le résultat des tests avec la ws-6.1.4 :

- Pour les boitiers "Pilote_Soc" tout fonctionne parfaitement
- Pour les boitiers "Heatzy", aucune réponse lors d'un clic pour un changement d'état. De plus, ça mets hors service les changements d'état des boitiers "Pilote_Soc" pour quelques instant puis ça revient

Le fichier de diag en PJ

[config_entry-heatzy-5cfe5470bb8f0612e705c215359934ae.json.txt](https://github.com/cyr-ius/hass-heatzy/files/13929011/config_entry-heatzy-5cfe5470bb8f0612e705c215359934ae.json.txt)

**Comment by cyr-ius** [comment]
@magicbret , la chose va pas être aiser car il va falloir lancer des commandes au piff et voir si cela marche , j'ai une version ws-6.1.5 , il faudrait que tu l'installes.
Ensuite tu allumes les boitiers Heatzy en mode confort ou eco.
Et le download diagnostic ,  je tente 6 commandes diffrentes pour passer le mode en "stop"
Donc si tes convecteurs passent en mode stop c bon. on a une des six commandes qui marchent.
Il suffira de déposer le fichier de diag pour connaitre la bonne.

**Comment by cyr-ius** [comment]
@magicbret , j'ai fait évoluer le fichier de diagnostic pour essayer de trouver la bonne commande à passer pour pilote les version "heatzy"
Si tu as moins de mettre à jour ta version en ws-6.2.0 et comme la dernière fois  , allumer les modules "heatzy" en mode confort , et de cliquer sur le fichier de diagnostic. Si il repasse en mode stop. On est bon. Il faudra juste redéposser le fichier de diag.

**Comment by magicbret** [comment]
Re,
J'ai téléchargé et installé la version w-6.2.2. Les commandes lancées via HA ne fonctionne toujours pas. Par contre, quand je veux télécharger le fichier de diagnostic, j'ai un fichier html avec le contenu suivant: 500 Internal Server Error, Server got itself in trouble.
Par contre je ne suis pas sûr de comprendre quand tu dis "_cliquer sur le fichier de diagnostic. Si il repasse en mode stop. On est bon_", le fait de cliquer sur "télécharger le fichier de diagnostic" ne peut pas modifier l'état du boitier, du coup je ne comprends pas trop la manip à faire.

**Comment by agodet** [comment]
Bonjour @cyr-ius,
avec la version websocket en version ws-6.2.2, n'importe quelle commande envoyé (away/comfort/eco) met le raidateur heatzy dans un état bizarre. Je vérifie avec l'application heatzy qui affiche off et aucun preset.

**Comment by agodet** [comment]
Bonjour, @cyr-ius, j'ai vu que tu avais mergé la branche websocket dans master. Ma PR n'a pas été prise en compte. Peux-tu intégrer mes modifications ou souhaites-tu que je pousse une nouvelle PR basé sur master ?

Merci pour ta réponse.

**Comment by cyr-ius** [comment]
Bonjour @agodet , effectivement je suis passé à côté de  ta demande. 
J intègre cela de suite dans la 6.3.1-beta2

**Comment by agodet** [comment]
Bonjour,
j'ai une régression en passant sur la 6.3.1-beta2, je n'ai plus de remonté du hvac_action en heating (lorsqu'il chauffe) et plus de remonté du preset_mode lorsque le radiateur est en auto.

**Comment by cyr-ius** [comment]
> Bonjour, j'ai une régression en passant sur la 6.3.1-beta2, je n'ai plus de remonté du hvac_action en heating (lorsqu'il chauffe) et plus de remonté du preset_mode lorsque le radiateur est en auto.

As tu le même soucis avec la 6.3.1-beta4

**Comment by agodet** [comment]
Oui pareillement.

**Comment by cyr-ius** [comment]
Tu as tjrs de soucis , j'ai sorti la 6.3.2
sinon , il faudrait me déposer le ficheir de diagnostic , dans le différente situation et captude d'écra si possible

**Comment by magicbret** [comment]
Hello,

Après plusieurs mois où j'étais resté en 5.9.7 sans aucun soucis, j'ai décidé de mettre à jour vers la 6.3.2. Malheureusement j'ai toujours mon problème ou 2 boitier sur 4 fonctionnent (pour rappel, j'ai 2 boitiers dont le modèle est "Heatzy" et 2, plus récents, où le modèle est "Pilote_soc".
J'ai voulu retourner vers la version 5.9.7 mais je suis incapable de me rappeler comment j'ai fait :)

**Comment by cyr-ius** [comment]
Peux tu installer la version 6.3.3 qui debug la version diagnostic et ensuite me déposer la log de debug et la log de diagnostic car normalement la version 6.x utiliser le mode websocket pour les convecteurs compatibles et l'ancien mode pour les autres. Donc transparent pour toi

**Comment by cyr-ius** [comment]
> > Peux tu installer la version 6.3.3 qui debug la version diagnostic et ensuite me déposer la log de debug et la log de diagnostic car normalement la version 6.x utiliser le mode websocket pour les convecteurs compatibles et l'ancien mode pour les autres. Donc transparent pour toi
> 
> Hello, ce sont bien ces fichiers là ? [ [home-assistant_heatzy_2024-11-25T12-12-36.509Z.log](https://github.com/user-attachments/files/17902844/home-assistant_heatzy_2024-11-25T12-12-36.509Z.log) [config_entry-heatzy-5cfe5470bb8f0612e705c215359934ae.json](https://github.com/user-attachments/files/17902845/config_entry-heatzy-5cfe5470bb8f0612e705c215359934ae.json) ](url)

Essaye la version 6.3.4-beta1 , je pense que cela devrait marcher . Fait moi un retour si OK , je ferais une version définitive

**Comment by magicbret** [comment]
Hello,

Alors ca semble bon avec la version 6.3.4-beta1. J'ai vu que tu avais déposé une beta4 et je l'ai testé mais après reload de HA, je n'avais plus aucun statut des boitiers.
J'ai fais un rollback vers la beta1 et c'est OK. Par contre il y a une latence sur l'affichage du statut sur la carte dans HA, en revanche en regardant en même temps l'application Heatzy sur le téléphone, l'envoi de la commande via HA se réflète presque instantanément sur l'appli heatzy.
Merci pour cette version :)

**Comment by cyr-ius** [comment]
La version ultime est la beta6.
Tu auras tjrs un petit décalage.  Car le tout premier modèle,  j utile l API historique alors que pour les modèles 2 et plus,  j utilise le websocket qui est lui instantané
