### ISSUE TITLE
Heatzy INEA

### ISSUE THREAD

**Issue by EddyF986** [cyr-ius/hass-heatzy#57]
Hi,

Thank you for this repo.
I have one heatzy Pilot and two heatzy Inea in my home installation. For the pilot, it's okay, it work great but not the case for the Inea. Is it planned to integrate the Inea someday ?

Thanks!

**Comment by cyr-ius** [comment]
Please upload diagnostic file

**Comment by EddyF986** [comment]
[config_entry-heatzy-15a9a7f4699970f043b509c4e067104d.json](https://github.com/cyr-ius/hass-heatzy/files/15167452/config_entry-heatzy-15a9a7f4699970f043b509c4e067104d.json)

This is my diagnostic file.
Thanks

**Comment by cyr-ius** [comment]
please try 6.3.1-beta1 version
