### ISSUE TITLE
Heatzy down?

### ISSUE THREAD

**Issue by clacheu** [cyr-ius/hass-heatzy#58]
Hello everyone, a few hours ago, the integration started to fail, and it is no longer able to connect to my 4 Heatzy Pilot modules. However, I can still control them using the Heatzy app. It seems that the issue could be related to the API? I didn't activate the logs, so I'm unable to provide more specific details, sorry. Are other people experiencing this issue? I'll keep you updated on any developments.

**Comment by clacheu** [comment]
Don't know if it could be related : 

Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:205
Integration: Thermostat ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 10:16:59 (8 occurrences)
Last logged: 10:16:59
•	HVAC_MODE_HEAT was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/rospogrigio/localtuya/issues
•	HVAC_MODE_OFF was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/rospogrigio/localtuya/issues
•	SUPPORT_PRESET_MODE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/rospogrigio/localtuya/issues
•	SUPPORT_TARGET_TEMPERATURE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/rospogrigio/localtuya/issues
•	SUPPORT_TARGET_TEMPERATURE_RANGE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE_RANGE instead, please create a bug report at https://github.com/rospogrigio/localtuya/issues

**Comment by AlainEspe** [comment]
Same problem

**Comment by clacheu** [comment]
Now it seems to work again, very weird, maybe a false alarm
