### ISSUE TITLE
inea integration

### ISSUE THREAD

**Issue by jms92100** [cyr-ius/hass-heatzy#60]
**Model**
inea

**Describe the bug**

does seem to be connected but is there

**Diagnostics & Debug file**
`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.5.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "6.6.25-haos",
    "supervisor": "2024.04.4",
    "host_os": "Home Assistant OS 12.2",
    "docker_version": "25.0.5",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "nodered": {
      "documentation": "https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/custom_integration/",
      "version": "4.0.0",
      "requirements": []
    },
    "schedule_state": {
      "documentation": "https://github.com/aneeshd/schedule_state",
      "version": "0.19.4",
      "requirements": [
        "portion==2.4.0"
      ]
    },
    "heatzy": {
      "documentation": "https://github.com/cyr-ius/hass-heatzy",
      "version": "6.1.2",
      "requirements": [
        "heatzypy==2.2.0"
      ]
    },
    "localtuya": {
      "documentation": "https://github.com/rospogrigio/localtuya/",
      "version": "5.2.1",
      "requirements": []
    },
    "pollens": {
      "documentation": "https://github.com/chris60600/pollens-home-assistant",
      "version": "2023.06.01",
      "requirements": []
    },
    "freebox_player": {
      "documentation": "https://github.com/Pouzor/freebox_player",
      "version": "1.0.6",
      "requirements": []
    },
    "rte_ecowatt": {
      "documentation": "https://github.com/kamaradclimber/rte-ecowatt",
      "version": "0.6.3",
      "requirements": [
        "Async-OAuthlib==0.0.9"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "average": {
      "documentation": "https://github.com/Limych/ha-average",
      "version": "2.3.1",
      "requirements": [
        "colorlog==6.7.0"
      ]
    },
    "huawei_solar": {
      "documentation": "https://github.com/wlcrs/huawei_solar/wiki",
      "version": "1.3.3",
      "requirements": [
        "huawei-solar==2.2.9"
      ]
    },
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.7.3",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "measureit": {
      "documentation": "https://github.com/danieldotnl/ha-measureit",
      "version": "0.5.0",
      "requirements": [
        "croniter==2.0.2"
      ]
    }
  },
  "integration_manifest": {
    "domain": "heatzy",
    "name": "Heatzy",
    "codeowners": [
      "@cyr-ius"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/cyr-ius/hass-heatzy",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/cyr-ius/hass-heatzy/issues",
    "loggers": [
      "heatzypy"
    ],
    "requirements": [
      "heatzypy==2.2.0"
    ],
    "version": "6.1.2",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "data": {
        "username": "**REDACTED**",
        "password": "**REDACTED**"
      },
      "options": {}
    },
    "bindings": {
      "devices": [
        {
          "protoc": 3,
          "ws_port": 8080,
          "port_s": 8883,
          "gw_did": null,
          "host": "**REDACTED**",
          "sleep_duration": 0,
          "port": 1883,
          "mcu_soft_version": "00000001",
          "product_key": "fc89066ee74c4149a9beb37d4ea93604",
          "state_last_timestamp": 1714973936,
          "role": "special",
          "is_sandbox": true,
          "type": "normal",
          "product_name": "INEA",
          "is_disabled": false,
          "mcu_hard_version": "00000001",
          "wifi_soft_version": "04020028",
          "dev_alias": "bureau",
          "mesh_id": null,
          "is_online": true,
          "dev_label": [],
          "wss_port": 8880,
          "remark": "range=2|isdelete=1|gid=0|groupname=|grouprange=0",
          "did": "cJWFzSaAuQw2NU687Li5Bi",
          "mac": "**REDACTED**",
          "passcode": "**REDACTED**",
          "wifi_hard_version": "00ESP826",
          "is_low_power": false
        }
      ]
    },
    "devices": {
      "cJWFzSaAuQw2NU687Li5Bi": {
        "protoc": 3,
        "ws_port": 8080,
        "port_s": 8883,
        "gw_did": null,
        "host": "**REDACTED**",
        "sleep_duration": 0,
        "port": 1883,
        "mcu_soft_version": "00000001",
        "product_key": "fc89066ee74c4149a9beb37d4ea93604",
        "state_last_timestamp": 1714973936,
        "role": "special",
        "is_sandbox": true,
        "type": "normal",
        "product_name": "INEA",
        "is_disabled": false,
        "mcu_hard_version": "00000001",
        "wifi_soft_version": "04020028",
        "dev_alias": "bureau",
        "mesh_id": null,
        "is_online": true,
        "dev_label": [],
        "wss_port": 8880,
        "remark": "range=2|isdelete=1|gid=0|groupname=|grouprange=0",
        "did": "cJWFzSaAuQw2NU687Li5Bi",
        "mac": "**REDACTED**",
        "passcode": "**REDACTED**",
        "wifi_hard_version": "00ESP826",
        "is_low_power": false,
        "updated_at": 1714957536,
        "attr": {
          "SEN_TIME": 60,
          "LOCK_C": 0,
          "p4_data11": 85,
          "p4_data10": 84,
          "p4_data12": 85,
          "minute": 5,
          "on_off": 1,
          "mode": "eco",
          "p5_data2": 85,
          "p3_data9": 0,
          "TEMP_COM": 3,
          "p7_data7": 21,
          "p5_data10": 84,
          "p5_data11": 85,
          "p7_data2": 85,
          "p5_data6": 0,
          "p7_data1": 85,
          "p7_data8": 0,
          "p7_data9": 0,
          "cur_tempH": 0,
          "p3_data2": 85,
          "cur_tempL": 175,
          "p3_data3": 85,
          "SIN_WIRE": 0,
          "p5_data1": 85,
          "p3_data8": 0,
          "p5_data3": 85,
          "p5_data4": 5,
          "p5_data5": 0,
          "PRO_TEMP": 0,
          "p5_data7": 21,
          "p5_data8": 0,
          "p5_data9": 0,
          "p3_data1": 85,
          "p3_data6": 0,
          "p3_data7": 21,
          "p3_data4": 5,
          "p3_data5": 0,
          "eco_tempH": 0,
          "eco_tempL": 165,
          "p6_data12": 85,
          "p6_data11": 85,
          "p6_data10": 84,
          "DATA1": 1,
          "p1_data10": 84,
          "DATA2": 104,
          "p2_data9": 0,
          "p2_data8": 0,
          "p2_data3": 85,
          "p2_data2": 85,
          "p2_data1": 85,
          "p2_data7": 21,
          "p2_data6": 0,
          "p2_data5": 0,
          "p2_data4": 5,
          "p6_data7": 21,
          "p6_data6": 0,
          "p6_data5": 0,
          "p6_data4": 5,
          "p6_data3": 85,
          "p6_data2": 85,
          "p6_data1": 85,
          "p6_data9": 0,
          "p6_data8": 0,
          "p1_data4": 5,
          "p1_data5": 0,
          "p1_data6": 0,
          "p1_data7": 21,
          "p1_data1": 85,
          "p1_data2": 85,
          "p1_data3": 85,
          "p1_data8": 0,
          "p1_data9": 0,
          "p3_data10": 84,
          "p3_data11": 85,
          "p3_data12": 85,
          "cft_tempH": 0,
          "cft_tempL": 180,
          "WIN_TIME": 0,
          "hour": 3,
          "timer_switch": 1,
          "p4_data1": 85,
          "p4_data3": 85,
          "p4_data2": 85,
          "p4_data5": 0,
          "p4_data4": 5,
          "p4_data7": 21,
          "p4_data6": 0,
          "p4_data9": 0,
          "p4_data8": 0,
          "p2_data12": 85,
          "p2_data11": 85,
          "p2_data10": 84,
          "week": 1,
          "p5_data12": 85,
          "p7_data4": 5,
          "p7_data5": 0,
          "p7_data6": 0,
          "p7_data3": 85,
          "p1_data12": 85,
          "p7_data10": 84,
          "p7_data11": 85,
          "p7_data12": 85,
          "p1_data11": 85
        }
      }
    }
  }
}`

**Additional context**

puisque le français est de mise , le json est assez explicite . Ce  n'est pas un bug mais un moyen de rajouter si possible l'integration inea au plugin

**Comment by cyr-ius** [comment]
Cet issue fait doublon avec la #57 
Inea a été intégré dans la version 6.3.1-beta1
J attends un retour pour savoir si cela est fonctionnelle

**Comment by jms92100** [comment]
Merci de la réponse 
Si je peux la tester , ce sera avec plaisir. (je n'ai qu'un inea pour l'instant)

**Comment by jms92100** [comment]
Merci de la réponse 
Si je peux la tester , ce sera avec plaisir. (je n'ai qu'un inea pour l'instant)

**Comment by cyr-ius** [comment]
@jms92100 , Tu peux facilement tester cela ,il suffit dans HACS de.selectionner l addon heatzy, de cliquer sur les 3points en haut à droite. ReTéléchargement  et de cocher beta version
