### ISSUE TITLE
Changer configuration suite changement de mot de passe

### ISSUE THREAD

**Issue by Nayou09** [cyr-ius/hass-heatzy#62]
Salut!

Tout d'abord bravo pour le super travail!

Ensuite j'aimerai juste faire une petite remarque : Comment qu'on fait quand on est stupide comme moi, et qu'on a pas enregistré quelque part le mot de passe de l'appli, qu'on a du reset le mot de passe...

Je ne vois nul part la possibilité de changer le mot de passe de l'entrée créée dans HA. Seule possibilité:  Supprimer l'entré créée (et donc les appareils, et comme j'ai créé plein d'automatisation et de switch sur les appareils...).

Est-ce qu'il y a une possibilité de changer le mot de passe dans l'intégration? ou je vais devoir tout me retaper à la main (ca m'apprendra a ne pas noter mes mots de passes....)

Merci et bonne soirée!

**Comment by cyr-ius** [comment]
Non pas de possibilité à faire dans l'appli du téléphone. C'est valable pour toutes les intégrations HA
