### ISSUE TITLE
Heatzy Pilote Pro

### ISSUE THREAD

**Issue by n4ckz** [cyr-ius/hass-heatzy#63]
Hello,

Is there a plan to include compatibility with the Heatzy Pilote Pro units in a future update?

Thank you,

**Comment by abusatif** [comment]
Hello,

Indeed I would have the same need regarding the acquisition of a new Pilote Pro module

THANKS

**Comment by albanlud** [comment]
That would be AWESOME 
Thanks a lot in advance !

**Comment by abusatif** [comment]
Bonjour,

Je vois que tu as clôturé le sujet sur le Heatzy Pilote Pro et que tu as fait une mise à jour en 6.3.3.
J'ai bien fait la mise à jour mais Heatzy Pro n'est toujours pas reconnu.
![Capture heatzy](https://github.com/user-attachments/assets/7d9df4e4-fe46-467d-a812-15907f7f9cb2)

J'ai essayé de désinstallé et réinstallé l'intégration Heatzy en supprimant mon compte et en le rajoutant mais toujours pareil.
Est ce que tu as clôturé car tu ne fera pas cette mise à jour pour le Heatzy Pro ou est ce que j'ai un soucis quelques part et tu as bien intégré cette mise à jour dans la 6.3.3. Après dans le détail de la mise à jour je ne vois pas que tu parle du Heatzy Pro donc c'est peut être normal.

Merci à toi.

Cordialement.
