### ISSUE TITLE
Heatzy entities become unavailable

### ISSUE THREAD

**Issue by flyingtortue** [cyr-ius/hass-heatzy#65]
Model:
Heatzy Pilote
Pilote_Soc_C3
by Heatzy
Firmware: 04030C33 

Testé sur HAOS version 2024.10.1 et version 2024.9.3 avec les même constats.

Cela a fonctionné pendant 2 jours et depuis hier, les entités sont indiquées "become unavailable"

J'ai tenté la désinstallation/réinstallation de l'intégration et la reconnexion au compte Heatzy.

La connection fonctionne et le device et les 2 entités sont bien découvert mais le device est directement vu comme ''unavailable''.
Les actions sur l'équipement ne fonctionnent pas.

Le téléchargement du fichier de diagnostic ne fonctionne pas. (il fonctionne pour les autres intégrations)

Debug log en fichier joint.

Merci d'avance pour l'aide apportée.

[heatzy_debug.txt](https://github.com/user-attachments/files/17266696/heatzy_debug.txt)

**Comment by flyingtortue** [comment]
Petite Update:

Ce matin je note que HA m'indique que le radiateur est vu à nouveau mais indique ''heating'' alors qu'il ne l'est pas.

Aucun changement fait coté HA.

Je relance l'intégration et une des deux entités disparait et pour celle qui reste (climate.couloir) les actions entrainent ces erreurs:
Failed to perform the action climate/set_hvac_mode. '>' not supported between instances of 'NoneType' and 'int'
Failed to perform the action climate/set_preset_mode. '>' not supported between instances of 'NoneType' and 'int'

**Comment by cyr-ius** [comment]
Peux tu installer la version 6.3.3 (qui corrige le mode diagnostic) et m'envoyer la log de debug et de diagnostic

**Comment by cyr-ius** [comment]
Fixer en 6.4.0-beta4
