### ISSUE TITLE
Stability issues reported within the logs

### ISSUE THREAD

**Issue by AGeille** [cyr-ius/hass-heatzy#67]
**Model**
Raspberry Pi5 with HAOS

**Describe the bug**
Je viens de tout installer avec versatile thermostat. A dispo si besoin

**Diagnostics & Debug file**
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
First occurred: 10:05:23 PM (4 occurrences)
Last logged: 10:06:43 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 280, in get
    data = await info.config_entry_diagnostics(hass, config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatzy/diagnostics.py", line 44, in async_get_config_entry_diagnostics
    coordinator = hass.data[DOMAIN][entry.entry_id]
                  ~~~~~~~~~^^^^^^^^
KeyError: 'heatzy'

**Additional context**

<!--Add any other context about the problem here.
Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 9:21:03 PM (1 occurrences)
Last logged: 9:21:03 PM

Detected blocking call to import_module with args ('custom_components.heatzy',) in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)

**Comment by AGeille** [comment]
Si je comprends bien ça semble être liée à la connexion à mon compte qui marche très bien j'ai pu intégrer tous mes devices.

**Comment by AGeille** [comment]
Bonjour, ça n'empêche pas le tout de fonctionner mais ça remonte une erreur
qui est liée au script python permettant de se connecter avec ses
credentials heatzy.

Le mer. 20 nov. 2024, 06:38, carlos16196 ***@***.***> a
écrit :

**Comment by carlos16196** [comment]
Ok, donc le problème de stabilité n’est pas lié à ce log. Mais du coup je ne suis pas vraiment sûr que j’ai le même problème.

Je vais essayer de creuser un peu plus d’où vient la perte de connexion périodique de ces modules. J’ai vu autre part que ça pouvait être lié à mon frontend de home-assistant. A voir.

merci.

**Comment by cyr-ius** [comment]
J'ai corrigé le mode diagnostic. Voir la version 6.3.3

**Comment by AGeille** [comment]
j'ai eu ce message suite à la mise à jour. Trop pour dire si oui ou non
cela un impact sur le fonctionnement des thermostats versatile
Core 2024.11.3
Supervisor 2024.11.4
Operating System 13.2
Interface utilisateur 20241106.2


Enregistreur: homeassistant.util.loop
Source: util/loop.py:77
S'est produit pour la première fois: 10:52:39 (1 occurrences)
Dernier enregistrement: 10:52:39

Detected blocking call to import_module with args
('custom_components.heatzy',) in
/usr/src/homeassistant/homeassistant/loader.py, line 1071:
ComponentProtocol, importlib.import_module(self.pkg_path) inside the event
loop; This is causing stability issues. Please create a bug report at
https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For
developers, please see
https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last): File "<frozen runpy>", line 198, in
_run_module_as_main File "<frozen runpy>", line 88, in _run_code File
"/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py",
line 209, in main exit_code = runner.run(runtime_conf) File
"/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return
loop.run_until_complete(setup_and_run_hass(runtime_config)) File
"/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in
run_until_complete self.run_forever() File
"/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in
run_forever self._run_once() File
"/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88,
in _run self._context.run(self._callback, *self._args) File
"/usr/src/homeassistant/homeassistant/setup.py", line 165, in
async_setup_component result = await _async_setup_component(hass, domain,
config) File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in
_async_setup_component component = await integration.async_get_component()
File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in
async_get_component comp = self._get_component() File
"/usr/src/homeassistant/homeassistant/loader.py", line 1071, in
_get_component ComponentProtocol, importlib.import_module(self.pkg_path)

**Comment by carlos16196** [comment]
Du coup mes entités heatzy son maintenant stable et je n'ai plus le problème "became unavailable" dans l'historique. je suis persuadé que la mise à jour a joué un rôle puisque je n'ai rien fait d'autre. merci.

**Comment by AGeille** [comment]
@cyr-ius j'ai eu ça aujourd'hui... 

Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.heatzy.coordinator
Source: helpers/update_coordinator.py:414
intégration: Heatzy (documentation, problèmes)
S'est produit pour la première fois: 22:00:09 (1 occurrences)
Dernier enregistrement: 22:00:09

Error fetching heatzy data: Invalid response from API: bindings not retrieved (502)

**Comment by cyr-ius** [comment]
L'erreur de binding est lié au serveur Heatzy qui n'a pas répondu
