### ISSUE TITLE
Heatzy pro

### ISSUE THREAD

**Issue by Cedriclekine** [cyr-ius/hass-heatzy#69]
Salut à tous,
Je viens d’installer des heatzy thermostat pro.
À priori la température n’est pas remontée. Et je ne trouve sous HA que les switch pour les verouiller. Je loupe quelque chose? Je pensais pouvoir les mettre en mode confort et arret

**Comment by cyr-ius** [comment]
Merci de mettre les fichiers de debug et diagnostic (je suis pas magicien)

**Comment by Cedriclekine** [comment]
[config_entry-heatzy-01JDWKA2NT896QR0039XXX47GA.json](https://github.com/user-attachments/files/17962744/config_entry-heatzy-01JDWKA2NT896QR0039XXX47GA.json)
Voici le fichier de diagnostic (la quiche en info que je suis ne sais pas trouver le fichier de debug)
En fait je ne vois que le switch qui locke les heatzy dans HA, je n’ai pas l’impression de pouvoir controler le mode (confort/eco/off)
Mille mercis pour l’aide que tu pourrais procurer :-)

**Comment by cyr-ius** [comment]
Tu trouveras la version 6.3.4-beta2 qui intégre  le module Pilote Pro. Merci d'essayer les différentes fonctions et de me faire un retour.  Si cela est OK , je te rajouterai aussi de nouveau capteur pour l'humidité et la détection des ouvertures

**Comment by cyr-ius** [comment]
J'ai fait une version 6.3.4-beta3 avec  cpateur d'humidité et fenetre

**Comment by Cedriclekine** [comment]
[home-assistant_2024-11-30T12-05-27.651Z.log](https://github.com/user-attachments/files/17965394/home-assistant_2024-11-30T12-05-27.651Z.log)
L’installation ou l’usage ne se passe pas comme prevu je pense 🧐 (merci pour la réactivité quand meme) j’ai une erreur au demarrage`

**Comment by Cedriclekine** [comment]
Tout fonctionne, avec toujours ce truc chiant des heatzy: si je suis à température, il passe en hors gel (mode auto sur homekit) 
Petit lag parfois sur homekit

**Comment by cyr-ius** [comment]
J ai déposé la beta6. Je comprends pas trop cette histoire de hors gel. Pouvez vous être plus précis ?

**Comment by Cedriclekine** [comment]
C’eset un fonctionnement du heatzy, quand on est à température il passe de mode confort à hors gel (et lieu de off chez les concurrents). Mais homekit reste en mode « chauffer ». En soit ce n’est pas grave, ca repasse en chauffage quand la température redescend mais si on regarde homekit (ou home assistant) on ne sait pas trop dans quel état il est.

**Comment by cyr-ius** [comment]
Peux tu tester la version 6.4.0-betaX , je viens en plus d'ajouter le sensor d'humidité sur le thermostat

**Comment by abusatif** [comment]
Bonjour,

Tout d'abord merci cyr-ius pour tout le travail accompli. J'aurais deux petites question.
J'utilise la dernière version beta 6.4.1 beta 2.
- Je vois bien le taux d'humidité apparaitre sur le climate du thermostat mais est il possible d'avoir un sensor à part pour pouvoir l'afficher sur une carte à part? En effet j'utilise custom:simple-thermostat et ca me permettrait de l'afficher.
- Deuxième demande j'utilise la carte (scheduler card) pour programmer tous mes chauffages (j'ai du tado et du heatzy), mais avec le pilote pro il y a deux réglages de température possible (la confort et la eco) et donc lorsque je programme une température avec scheduler ca ne modifie pas la température de consigne (ni l'une ni l'autre, je pense que ce n'est pas le même terme qu'un thermostat standard à une consigne), y'a t'il une solution pour que cela puisse fonctionner ensemble?

Merci à toi.

Cordialement.

**Comment by cyr-ius** [comment]
l'humidité est un attribut  du sensor ,

![image](https://github.com/user-attachments/assets/c193fc53-81da-4917-9aad-b8e7bfda9581)

Il me semble possible d'afficher un attribut avec simple-thermostat


```
cards:
  - type: 'custom:simple-thermostat'
    entity: climate.my_room
    step_size: 1
    sensors:
      - entity: sensor.fibaro_system_fgwpef_wall_plug_gen5_energy
      - entity: sensor.fibaro_system_fgwpef_wall_plug_gen5_power
        name: Energy today
      - attribute: current_humidity
        name: Humidité
```


Concernant le second point , j'essayerais d'utiliser un script qui appelerait le service (ou maintenant Action) qui règle tes températures. Dans scheduler card , tu as la notion d'utiliser des actions.
Par ma part , j'ai longtemps utiliser la scheduler card mais depuis qu'il existe une option scheduler intégré à HomeAssistant , j'ai remplacé celle-ci pour utiliser le mode natif.

![image](https://github.com/user-attachments/assets/594c33c8-2c7a-48b1-b17d-a6a91c7edbde)

le mode natif:
![image](https://github.com/user-attachments/assets/22c11743-9867-49ec-aabc-8688e47a844d)

**Comment by abusatif** [comment]
Merci, effectivement je n'avais pas la façon d'afficher le taux d'humidité mais c'est tout bon grâce à toi.
Je vais également le planificateur natif voir ce que je peux faire.

Merci à toi pour ta réactivité et surtout tout le travail fait pour ces modules Heatzy.

**Comment by cyr-ius** [comment]
Tu peux aussi faire toi même ton sensor , tu vas sur Entrée et tu choisis template de sensor

et dans le state , tu sélection {{state_attr('climate.test_pilote_pro', 'humidity')}}


![image](https://github.com/user-attachments/assets/547a3c24-9968-40c1-be02-9d017b766b93)

**Comment by abusatif** [comment]
Merci, j'ai juste modifié la ligne de commande pour mettre current_humidity au lieu de humidity et cela fonctionne parfaitement. Ca permet d'avoir le signe % sur la carte du coup donc encore mieux. Je ne savais que l'ont pouvais recréer des capteur lié à l'appareil directement, je suis encore jeune sur HA.
Je vais maintenant m'attaquer à la programmation et voir laquelle des deux solution est la mieux car je ne connais pas encore le planificateur intégré.

Merci à toi.
