### ISSUE TITLE
Issue to connect to pilot the devise

### ISSUE THREAD

**Issue by pdecarde** [Cyr-ius/hass-heatzy#7]
Hi,
I'm trying this integration for the first time. The integration is working and the is discovering the entity. nevertheless impossible to get the preset_mode, nor to assign a new one. was trying via the dev interface and get the following attributes. status being "heat". trying via the interface is overwriting after few seconds.
I can't see any error in the HASS journal.

 hvac_modes:
  - heat
  - 'off'
min_temp: 7
max_temp: 35
preset_modes:
  - none
  - comfort
  - eco
  - away
current_temperature: null
preset_mode: null
friendly_name: HEATZY_XXXX
supported_features: 16

can you help me to find what is going wrong?

**Comment by Cyr-ius** [comment]
please enable debug mode in configuration.yaml
```
logger:
  logs:
    custom_components.heatzy: debug
```
