### ISSUE TITLE
Couleurs du mode Confort et Eco inversées.

### ISSUE THREAD

**Issue by auraveldt** [cyr-ius/hass-heatzy#73]
Salut,
Je découvre ton intégration après avoir installé mes Heatzy Pro, et je constate un petit soucis mineur.
Les couleurs du mode et Eco et Confort sont inversées sur l'entité climate.
La couleur pour régler la température du mode Eco est orange, tandis que celle du mode confort, donc plus chaud, est bleue.

C'est tout bête, mais ça porte à confusion.

En tout cas merci pour ton travail !

![Capture d’écran 2024-12-10 170150](https://github.com/user-attachments/assets/6fdbe02b-7bbc-4502-8d67-428b41ad039c)

**Comment by cyr-ius** [comment]
Cela peut paraitre bizarre mais c'est bien comme cela que les concepteurs de HA  ont intégré le thermostat

Voici le lien en 2023 du lancement du mode.
https://www.home-assistant.io/blog/2023/09/06/release-20239/#new-climate-humidifier-and-water-heater-entity-dialogs

A gauche (rouge) , à droite (bleu) comme l'eau chaude et l'eau froide dans nos maisons.
Je penses que tu rajoutes du chaud ou tu enlèves du froid....
