### ISSUE TITLE
Switch pour les heatzy pilote

### ISSUE THREAD

**Issue by TheTakylo** [cyr-ius/hass-heatzy#74]
j'ai un heatzy pilote standard (pas le pro) mais je ne trouve pas comment le configurer avec le thermostat de home assistant, il n'y a pas de switch pour activer le radiateur.
c'est moi qui ne trouve pas ou ce n'est pas possible ?

au passage, merci pour cette super intégration

**Comment by yohan900000** [comment]
pareil je trouve pas le switch

**Comment by cyr-ius** [comment]
Effectivement, il n'existe pas de switch car les Heatzy Pilote n'en possèdent pas. Comme je l'ai indiqué dans un autre issue, les heatzy pour s'arrêter se mettent sur un PRESET à STOP et s'allume sur PRESET COMFORT ou PRESET ECO.

Cependant il est possible de  faire un switch et ensuite d'émuler un thermostat si vous aves des sensors qui donne la température. C'est actuellement la configuration que j'utilise

Exemple:
Dans le menu Appareil et Service , aller sur Entrée,  ajouter une entrée de type Template Commutateur (switch)

Dans le modèle de valeur : indiquer l'attribut qui renvoit l'état quand celui-ci est alluimé
`{{ is_state('climate.violette', 'heat') }}`
Action de l'activation faite , Allumer l'apareil
Action de désactivation faite , Eteindre l'appareil

Le modèle de valeur sert à surveiller l'état de l'appareil si vous jouez par exemple avec l'appli heatzy ou autre chose.
Du coup , il recale toujours le switch dans la bonne position.

![image](https://github.com/user-attachments/assets/462bfc8d-5187-4e9a-be2a-7d3deb8e4930)

A savoir que  dans le code , j'ai fait le choix suivant: 
Le Climate Turn ON envoie un ordre PRESET COMFORT
Le climate Turn OFF envoie un PRESET STOP
(Comme vous pouvez le constater le mode ECO n'est pas employer, il fallait faire un choix lors du dev de l'addon)

Ensuite je crée un Thermostat , dans le même menu , ajouter une Entrée Thermostat
Je choisis mon capteur de Température, (un Lumi Aquara) , je choisis mon switch créé initialement et voilà un thermostat où vous pouvez régler la température , du coup le radiateur s'allume ou s'éteint en fonction.

![image](https://github.com/user-attachments/assets/b31b29f2-ca9f-4b43-a8c1-baa7807b3d8d)
![image](https://github.com/user-attachments/assets/aec3fefd-e3cc-45df-ac63-889552601eda)


Dans les automations , je n'utilise plus les PRESETS , mais si je veux baisser la température la nuit , je fais un climate.set_temperature , j'indique par exemple 17° à partir de 23h

**Comment by yohan900000** [comment]
Chaque fois que j'éteint mon nas, tous mes thermostat ne sont plus fonctionnel sur mon home assistant je ne comprend pas

**Comment by cyr-ius** [comment]
> Chaque fois que j'éteint mon nas, tous mes thermostat ne sont plus fonctionnel sur mon home assistant je ne comprend pas

Merci d'ouvrir une issue et d'être un peu plus explicatif. Ton HA est-il hébergé sur ton NAS .
Qu'est-ce que tu utilises comment Thermosat ? les template de HA ou autres..

Ne possèdant ni le don de voyance , ni de télépathie , je peux pas t'aider.
Moi à chaque fois que Yohan pète , je baille..

**Comment by yohan900000** [comment]
J'utilise un Heatzy Pilote 1 pour la gestion du chauffage, et mon Home Assistant est hébergé sur mon NAS Synology DS224+
![dfd](https://github.com/user-attachments/assets/58a2caa5-29b6-4445-b9ee-ff54d2e87b8f)
![Sans titre](https://github.com/user-attachments/assets/b3d825ed-61a8-48bb-948f-d55d82c70c90)

**Comment by cyr-ius** [comment]
Quand on regarde ta première capture , dans le journal, on voit écrit A été éteint par Home Assistant Core désactivation générique. Cela ne serait-ce pas ton pbl.

**Comment by cyr-ius** [comment]
Tu as peut être une autoation avec une action du type :  homeassistant.turn_off

**Comment by yohan900000** [comment]
Non car quand je clique sur chauffe ou sur auto il retourne sur le mode éteint. Non je n'est aucune automatisation. la dernière fois j'ai eu le même problème après un reboot de mon nas j'ai mi 1h à régler le problème j'ai fait que de supprimer remettre supprimer remettre changer les versions ect... mais la rien n'y fait. :/

**Comment by cyr-ius** [comment]
Ok , active le mode Debug de Heatzt, essaye de rallumer le Thermostat à plusieurs fois  et envoie moi la log ainsi que le fichier de diagnostic

**Comment by yohan900000** [comment]
Uploading WhatsApp Vidéo 2024-12-13 à 18.27.53_98716190.mp4…

**Comment by yohan900000** [comment]
Peux tu me dire comment active le mode Débug ? et ensuite comment avoir la log et le fichier diagnostic merci

**Comment by cyr-ius** [comment]
Tu cliques sur le composant Heatzy (1er capture) , tu veras ensuite à gauche dans le menu Actives l'enregistrement des journeaux 
![image](https://github.com/user-attachments/assets/28084a5a-71bc-4b19-bbdd-7a5f1d4d2ee4)


Quandtu cliques sur Stop cela le télécharge automatiquement.
Le fichier diagnostic , il faut cliquer sur les 3points , télécharger Diagnostic

**Comment by yohan900000** [comment]
[config_entry-heatzy-01JF0C9S6CSSKD9HZ81WMZA2C8.json](https://github.com/user-attachments/files/18129539/config_entry-heatzy-01JF0C9S6CSSKD9HZ81WMZA2C8.json)
[home-assistant_heatzy_2024-12-13T17-34-14.440Z.log](https://github.com/user-attachments/files/18129540/home-assistant_heatzy_2024-12-13T17-34-14.440Z.log)


voila mon diag et ma log

**Comment by cyr-ius** [comment]
Tu as une erreur sur ta template, tu as mis un "/" 

Template<template=({{ /states("sensor.thermometre_temperature_salon") }}°C) renders=508>

il faut que tu le retire ou tu l'échappe par un \
et je crois que l'erreur est sur  quelques thermostats

2024-12-13 18:26:59.598 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ /states("sensor.thermometre_temperature_salon") }}°C) renders=508>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 575, in ensure_valid
    self._compiled_code = self._env.compile(self.template)
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 3210, in compile
    compiled = super().compile(source)
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '/'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 748, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 625, in async_render
    compiled = self._compiled or self._ensure_compiled(limited, strict, log_fn)
                                 ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 829, in _ensure_compiled
    self.ensure_valid()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 577, in ensure_valid
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TemplateSyntaxError: unexpected '/'
2024-12-13 18:27:40.986 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities climate.thermostat_chambre_katerina are missing or not currently available

**Comment by yohan900000** [comment]
C'est dazns quel fichier que je doit modifie cela ?

**Comment by yohan900000** [comment]
/usr/src/homeassistant/homeassistant/helpers/template.py, je ne trouve pas ce fichier. Et ce qui me parait bizarre c'est que je n'est rien toucher manuellement

**Comment by cyr-ius** [comment]
Cela est dans ton template de thermostatt, là ou tu as essayé de récuper la température en °C alors que le heatzy ne le fait pas

**Comment by cyr-ius** [comment]
Dans ton menu "Entrée" , je suppose

**Comment by yohan900000** [comment]
Je fais des modifications je regarde mes erreurs si j'arrive à corriger et je te tiens au courant merci

**Comment by yohan900000** [comment]
c'est bon j'ai réussi je pense que chaque fois que je debranche ma box et le nas il se comprenne plus mdr mais pourtant j'arrive toujours à les gérer via l'appli officiel

**Comment by cyr-ius** [comment]
Effectivement maintenant la log est propre. et je vois bien que l e module heatzy fonctionne bien.
Après HA après un coupure électrique où la box internet et le nas part en vrille. Il faut être sûr que tu es bien IP fixe car si ta box démarre après le nas,. Tu peux avoir ta vm ou ton container sans IP. Bon je clos cette issue.
Rouvre une nouvelle si cela perture
