### ISSUE TITLE
slow state update

### ISSUE THREAD

**Issue by Gwenlad** [Cyr-ius/hass-heatzy#9]
Hello :)
thank a lot for this custom component  ! it works great, but I have to wait long time for the state update. 
If I turn ON my heater and OFF few second after it's like if the state was freeze, I have to wait few minutes to have an update. On the Heatzy app the state change and on my heater too, but not in HA.
I try to remove and reinstall hass-heatzy but it's still the same, I don't know what to do.
My internet connection is slow,  but my other device have not this problem.

Thank you ! merci ;)

**Comment by fbaticam** [comment]
Same problem for me.

**Comment by themaxx32000** [comment]
@Cyr-ius if set_preset_mode does not throw an exception we could update the status right away without waiting for the 60 second api-update-interval. As I just installed HomeAssistant today and I am not familiar with it, it might be easier for you to implement this..

**Comment by Cyr-ius** [comment]
I am not in favor of this solution. I prefer to send the command even if the API but a good minute to update. The command is executed without error. On the next HA refresh, the value will be correct.

However, I added a delay to slightly wait for the API update
